# docker-compose.yml - Rimozione del servizio Elasticsearch

version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic
      - ./scripts:/app/scripts
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/compliance_compass
      - SECRET_KEY=your_secret_key
      - DEBUG=true
      - USE_MOCK_ELASTICSEARCH=true
      - USE_SIMPLE_CHATBOT=true
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - compliance-network

  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=compliance_compass
    ports:
      - "5432:5432"
    networks:
      - compliance-network

  frontend:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./docker/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - compliance-network

networks:
  compliance-network:
    driver: bridge

volumes:
  postgres_data: