version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/compliance_compass
      - JWT_SECRET_KEY=compliance_compass_secret_key_development
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - db
      - elasticsearch
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - compliance_compass_network

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=compliance_compass
    networks:
      - compliance_compass_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - compliance_compass_network

  frontend:
    image: node:18
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm start"
    networks:
      - compliance_compass_network
    depends_on:
      - api

networks:
  compliance_compass_network:

volumes:
  postgres_data:
  elasticsearch_data: