version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: docker/Dockerfile.api  # Updated path to Dockerfile
    container_name: compliance-compass-api
    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
      - ./scripts:/app/scripts
      - ./docker:/app/docker  # Mount docker directory to ensure entrypoint is accessible
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/compliance_compass
      - JWT_SECRET_KEY=your_secret_key
      - DEBUG=true
      - CORS_ORIGINS=["http://localhost:3000","http://localhost:8000"]
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - compliance_compass_network

  db:
    image: postgres:14
    container_name: compliance-compass-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=compliance_compass
    ports:
      - "5432:5432"
    networks:
      - compliance_compass_network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: compliance-compass-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevent overwriting node_modules
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider  # For Node 16 compatibility
    ports:
      - "3000:3000"
    networks:
      - compliance_compass_network
    depends_on:
      - api

networks:
  compliance_compass_network:
    driver: bridge

volumes:
  postgres_data: